<?php

namespace Adarts;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-01 at 19:11:51.
 */
class DictionaryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Dictionary
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Dictionary;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Adarts\Dictionary::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        $this->object
            ->add("毛 abcfd")
            ->add("bcev")
            ->add("毛 主 席")
            ->add("主 导")
            ->add("习boss")
            ->confirm();
        du($this->object);

        // 测试深回归
        du($this->object->search('123毛 abcfwr'), 'result');

        // 测试失败指针
//        du($this->object->search('abd毛 主d 毛 主 导k'), 'result');

        // 测试未找到
//        du($this->object->search('abd毛习'), 'result');

        // 测试找到
//        du($this->object->search('abd习bosseee'), 'result');

    }

    /**
     * @covers Adarts\Dictionary::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Adarts\Dictionary::compress
     * @todo   Implement testCompress().
     */
    public function testCompress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
